test_eav:
    resource: "@TestEAVBundle/Resources/config/routing.yml"
    prefix:   /

malkos_extjs:
    resource: "@MalkosExtjsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

enviroment_eav:
    resource: "@EnviromentEavBundle/Resources/config/routing.yml"
    prefix:   /attribute