test_eav:
    resource: "@TestEAVBundle/Resources/config/routing.yml"
    prefix:   /

malkos_extjs:
    resource: "@MalkosExtjsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

padam87_attribute:
    resource: "@EnviromentEavBundle/Controller/"
    type:     annotation
    prefix:   /